#!/bin/sh

if [ ! -d "./.venv/" ]; then
    python3 -m venv .venv &&\
        source .venv/bin/activate &&\
        pip3 install -r ./requirements.txt
fi

rm -rf build/ &&\
    mkdir -p build &&\
    cp gitm.py build/gitm.py &&\
    python3 gitm.py $@