#!/bin/sh
SCRIPT_NAME="gitm"
COMMAND_NAME="gitm"
DESTINATION="/usr/local/bin"

echo "installing to $DESTINATION/$COMMAND_NAME" &&\
    sudo ln -sf "$(pwd)/$SCRIPT_NAME" "$DESTINATION/$COMMAND_NAME" &&\
    chmod +x "$SCRIPT_NAME" &&\
    echo "$COMMAND_NAME installed"