#!/bin/sh

if [ ! -d "./.venv/" ]; then
    python3 -m venv .venv &&\
        source .venv/bin/activate &&\
        pip3 install -r ./requirements.txt
fi

SCRIPT_NAME="gitm.py"
COMMAND_NAME="gitm"
DESTINATION="/usr/local/bin"

echo "installing to $DESTINATION/$COMMAND_NAME" &&\
    sudo ln -sf "$(pwd)/$SCRIPT_NAME" "$DESTINATION/$COMMAND_NAME" &&\
    chmod +x "$SCRIPT_NAME" &&\
    echo "$COMMAND_NAME installed"