#!/bin/bash
source .venv/bin/activate \
    && rm -rf build/tests/ \
    && mkdir -p build \
    && cp -r tests build/tests \
    && cp gitm.py build/tests/gitm.py \
    && cd build/tests \
    && python3 gitm.py update