#!/bin/sh
SCRIPT_NAME="gitm"
COMMAND_NAME="gitm"
DESTINATION="/usr/local/bin"

echo "uninstalling $DESTINATION/$COMMAND_NAME" &&\
    sudo rm "$DESTINATION/$COMMAND_NAME" &&\
    echo "$COMMAND_NAME uninstalled"